//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476.Devoir3.Samuel.Octeau.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Details = new HashSet<Order_Detail>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        [Required]
        public Nullable<int> SupplierID { get; set; }
        [Required]
        public Nullable<int> CategoryID { get; set; }
        [Required]
        public string QuantityPerUnit { get; set; }
        [Required]
        public Nullable<decimal> UnitPrice { get; set; }
        [Required]
        public Nullable<short> UnitsInStock { get; set; }
        [Required]
        public Nullable<short> UnitsOnOrder { get; set; }
        [Required]
        public Nullable<short> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
        [Required]
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Details { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
